@echo off

if not exist %SDKFOLDER% goto:nosdk goto nosdk

pushd .
cd symbian\src\
bldmake bldfiles
call abld reallyclean gcce urel
call abld build gcce urel
popd

if exist appuifw2.sis del appuifw2.sis
mkdir appuifw2\resource appuifw2\python appuifw2\sys\bin
copy %SDKFOLDER%\Epoc32\release\gcce\urel\_appuifw2.pyd appuifw2\sys\bin\
c:\python22\python.exe -O c:\python22\lib\compileall.py python
copy python\resource\appuifw2.pyo appuifw2\resource\appuifw2.pyc
rem UID is autogenerated by ensymble based on the "appuifw2" directory name
ensymble.py simplesis --caption=appuifw2 --version=1.0.0 --drive=C --vendor="Arkadiusz Wahlig" --verbose appuifw2 appuifw2_1.0.0_3rdEd_unsigned_testrange.sis
rmdir /s/q appuifw2

goto exit


:nosdk
echo run init_envs.bat first!

:exit
